# define the service name and the image to use
name: catalog-service
services:
  mongodb:
    image: mongo:latest
    container_name: catalog-service-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--username", "admin", "--password", "admin123", "--authenticationDatabase", "admin", "--eval", "db.runCommand({ ping: 1 }).ok" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo_data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
  minio:
    image: minio/minio
    container_name: catalog-service-minio
    ports:
      - '9000:9000'
      - '9002:9002'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9002"
    volumes:
      #      - D:\minio-data:/data
      - D:/docker-data/minio-data:/data
  catalog-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catalog-service
    restart: on-failure
    ports:
      - '8082:8082'
    environment:
      SPRING_MONGODB_URI: "mongodb://catalog_user:catalog_password@mongodb:27017/catalog_db?authSource=catalog_db"
      SPRING_DATA_MONGODB_URI: "mongodb://catalog_user:catalog_password@mongodb:27017/catalog_db?authSource=catalog_db"
      MONGODB_URI: "mongodb://catalog_user:catalog_password@mongodb:27017/catalog_db?authSource=catalog_db"
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: book-images
      USER_SERVICE_URL: http://host.docker.internal:8081
    depends_on:
      mongodb:
        condition: service_healthy
      minio:
        condition: service_started

volumes:
  mongo_data:
  minio_data:
